#!/bin/bash
# generated by ll-helper

LD_PATH=$(find $PREFIX -name "*.so*" | xargs -rn1 dirname | grep -v "/lib/jvm" | sort -u| paste -sd :)
echo LD_PATH=$LD_PATH >&2
find $PREFIX -type f -executable|xargs -rn1 env LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LD_PATH" ldd|grep "not found"| grep -oP "^\s*\K\S+"|sort -u
