#!/bin/bash
# generated by ll-helper

echo Generate Startup Script

PATCH_APP_PATH="s#/opt/apps/\S+/files#${PREFIX}#g"
PATCH_USR_PATH="s#/usr#$PREFIX#g"
PATCH_STARTUP="s#$REBASED_STARTUP#$LINGLONG_COMMAND#g"

STARTUP=$(cat $PREFIX/share/applications/*.desktop | grep '^Exec=' | head -n 1 | sed 's/^Exec=//g' | xargs -n 1 echo 2>/dev/null | head -n 1)
REBASED_STARTUP=$(echo $STARTUP | sed -E -e "$PATCH_APP_PATH" -e "$PATCH_USR_PATH")
echo STARTUP: ${STARTUP}
echo REBASED_STARTUP: ${REBASED_STARTUP}
echo BOOT: ${LINGLONG_COMMAND}
sed -i -E $PREFIX/share/applications/*.desktop -e "/Exec=/ $PATCH_APP_PATH" -e "/Exec=/ $PATCH_USR_PATH" -e "/Exec=/ $PATCH_STARTUP"

if od "$REBASED_STARTUP" -An -N2 -tx2 | grep -q "2123"; then
    echo Patch Script: ${STARTUP}
    sed -i -E -e "$PATCH_APP_PATH" "$REBASED_STARTUP"
fi

echo "exec ${REBASED_STARTUP} \$@" >>$LINGLONG_COMMAND
chmod +x $LINGLONG_COMMAND
