#!/bin/bash
# generated by ll-helper

# desktop文件补丁
STARTUP=`grep '^Exec=' $PREFIX/share/applications/*.desktop  | head -n 1|sed 's/^Exec=//g'|xargs -n 1 echo 2>/dev/null|head -n 1`
sed -i -E $PREFIX/share/applications/*.desktop -e "/Exec=/ s+/opt/apps/.*/files+${PREFIX}+g" -e "/Exec=/ s+/usr+$PREFIX+g" -e "/Exec=/ s+$STARTUP+$LINGLONG_COMMAND+g" 