#!/bin/bash
# generated by ll-helper


IMAGE=$(ls /opt/apps/com.todesk.linyaps/files/share/icons/hicolor/*/apps/* 2>/dev/null| head -n 1 | xargs -r basename -a)
ICON="${IMAGE%.*}"
if [ -n "$ICON" ];then
    echo Patch Desktop Icon Path
    sed -i -E $PREFIX/share/applications/*.desktop -e "/Icon=/ s+^Icon=.*$+Icon=${ICON}+g"
fi
