#!/bin/bash
# generated by ll-helper

echo Patch LD_LIBRARY_PATH
LD_PATH=$(find $PREFIX -name "*.so*" | xargs dirname | grep -v "/lib/jvm" | sort | uniq | paste -sd :)
echo "export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:$LD_PATH" | tee -a $LINGLONG_COMMAND
