#!/bin/bash
# generated by ll-helper

QT_PLUGIN_PATH=$(find $PREFIX/lib/x86_64-linux-gnu/qt5/plugins/ -name "*.so*" | xargs dirname | sort | uniq | paste -sd :)
if [ -n "$QT_PLUGIN_PATH" ]; then
    echo "export QT_PLUGIN_PATH=$QT_PLUGIN_PATH" | tee -a $LINGLONG_COMMAND
fi

QTWEBENGINE_RESOURCES_PATH="$PREFIX/share/qt5/resources"
if [ -d "$QTWEBENGINE_RESOURCES_PATH" ]; then
    echo QTWEBENGINE_RESOURCES_PATH=$QTWEBENGINE_RESOURCES_PATH
    echo "export QTWEBENGINE_RESOURCES_PATH=$QTWEBENGINE_RESOURCES_PATH" | tee -a $LINGLONG_COMMAND
    ln -svf $QTWEBENGINE_RESOURCES_PATH/* $PREFIX/bin
    ln -svf $QTWEBENGINE_RESOURCES_PATH/* $PREFIX/lib/x86_64-linux-gnu/qt5/libexec/
fi

QTWEBENGINE_LOCALES_PATH="$PREFIX/share/qt5/translations/qtwebengine_locales"
if [ -d "$QTWEBENGINE_LOCALES_PATH" ]; then
    echo "export QTWEBENGINE_LOCALES_PATH=$QTWEBENGINE_LOCALES_PATH" | tee -a $LINGLONG_COMMAND
    ln -svf $QTWEBENGINE_LOCALES_PATH $PREFIX/lib/x86_64-linux-gnu/qt5/libexec/
fi

QTWEBENGINEPROCESS_PATH="$PREFIX/lib/x86_64-linux-gnu/qt5/libexec/QtWebEngineProcess"
if [ -e "$QTWEBENGINEPROCESS_PATH" ]; then
    echo "export QTWEBENGINEPROCESS_PATH=$QTWEBENGINEPROCESS_PATH" | tee -a $LINGLONG_COMMAND
fi
QML2_IMPORT_PATH="$PREFIX/lib/x86_64-linux-gnu/qt5/qml"
if [ -e "$QML2_IMPORT_PATH" ]; then
    echo "export QML2_IMPORT_PATH=$QML2_IMPORT_PATH" | tee -a $LINGLONG_COMMAND
fi
