#!/bin/bash
# generated by ll-helper

# 图标补丁
IMAGE=$(ls /opt/apps/com.todesk.linyaps/files/share/icons/hicolor/*/apps/* | head -n 1 | xargs basename -a)
ICON="${IMAGE%.*}"
sed -i -E $PREFIX/share/applications/*.desktop -e "/Icon=/ s+^Icon=.*$+Icon=${ICON}+g"
