#!/bin/bash
# generated by ll-helper

if [ -d $PREFIX/lib/jvm ] || [ -n "$JAVA_HOME" ]; then
    if [ -z "$JAVA_HOME" ]; then
        if [ -d $PREFIX/lib/jvm/default-java/bin/java ]; then
            JAVA_HOME=$PREFIX/lib/jvm/default-java
        else
            JAVA_HOME=$PREFIX/lib/jvm/java-*-openjdk-amd64
        fi
    fi
    echo JAVA_HOME=$JAVA_HOME
    JAVA_PATH=$JAVA_HOME/bin
    if [ ! -e $JAVA_PATH/java ]; then
        echo ERROR: BAD JAVA_PATH=$JAVA_PATH >&2
    fi
    echo "export PATH=\$PATH:$JAVA_PATH" | tee -a $LINGLONG_COMMAND
    echo "export JAVA_HOME=$JAVA_HOME" | tee -a $LINGLONG_COMMAND
fi
