#!/bin/bash
# generated by ll-helper

echo Applying Patch: qpa

QT_PLATFORM_PATH="$PREFIX/lib/x86_64-linux-gnu/qt5/platforms"
if [ -d "$QT_PLATFORM_PATH" ]; then
    echo Patch QT_QPA_PLATFORM_PLUGIN_PATH
    echo "export QT_QPA_PLATFORM_PLUGIN_PATH=$QT_PLATFORM_PATH" | tee -a $LINGLONG_COMMAND
fi
